# Generated by Django 3.2 on 2021-04-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan', models.CharField(choices=[('1', 'premium'), ('2', 'gold'), ('3', 'diamond')], default='1', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('signalString', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('count', models.IntegerField()),
                ('manualbooleanfield', models.BooleanField()),
                ('time_when_boolean_field_changes', models.DateTimeField()),
                ('total_ratings', models.IntegerField()),
                ('no_of_ratings', models.IntegerField()),
                ('average_rating', models.FloatField()),
            ],
        ),
    ]
