# Generated by Django 3.2 on 2021-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='manualbooleanfield',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='no_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
