# Generated by Django 3.2 on 2021-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_person_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time_when_boolean_field_changes',
            field=models.DateTimeField(null=True),
        ),
    ]
