# Generated by Django 3.2 on 2021-04-08 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0005_alter_person_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='time_when_boolean_field_changes',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 7, 14, 12, 910711, tzinfo=utc)),
        ),
    ]
